language: python
dist: xenial

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "pypy3"

install:
    - pip install --upgrade setuptools coveralls
    - python setup.py develop

script:
    - coverage run --source=flowlogs_reader setup.py test

after_success:
    - coveralls
